/**
 * Generates public/sitemap.xml from src/data/tools.ts.
 *
 * - Single source of truth: every non-upcoming tool in TOOLS gets a
 *   /tools/:slug URL, so the sitemap can never drift from the router.
 * - Upcoming placeholders are EXCLUDED (they render a "coming soon" page
 *   and carry noindex via upcomingToolSeo()).
 * - Every URL gets a <lastmod> (today, UTC) so crawlers have a real
 *   freshness signal. changefreq/priority are kept for compatibility but
 *   Google largely ignores them.
 *
 * Runs automatically via the `prebuild` npm script and can be run
 * manually with `npm run sitemap`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SITE_URL = "https://pdfbrains.com";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const toolsPath = join(root, "src", "data", "tools.ts");
const outPath = join(root, "public", "sitemap.xml");

const source = readFileSync(toolsPath, "utf8");

// Each tool is a single-line object literal containing slug: "...".
// Match each object block, then filter out upcoming: true entries.
const blocks = source.match(/\{[^{}]*slug:\s*"[^"]+"[^{}]*\}/g) ?? [];

const slugs = [];
for (const block of blocks) {
  const slug = block.match(/slug:\s*"([^"]+)"/)?.[1];
  if (!slug) continue;
  if (/upcoming:\s*true/.test(block)) continue;
  slugs.push(slug);
}

slugs.sort();

if (slugs.length === 0) {
  console.error(`generate-sitemap: no tool slugs found in ${toolsPath}`);
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);

function url(loc, changefreq, priority) {
  return [
    "  <url>",
    `    <loc>${loc}</loc>`,
    `    <lastmod>${today}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    "  </url>",
  ].join("\n");
}

const lines = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  "<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand: it is",
  "     rebuilt from src/data/tools.ts on every build (npm run sitemap). -->",
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  url(`${SITE_URL}/`, "weekly", "1.0"),
  url(`${SITE_URL}/ai-assist`, "monthly", "0.6"),
  ...slugs.map((slug) => url(`${SITE_URL}/tools/${slug}`, "monthly", "0.8")),
  "</urlset>",
  "",
];

writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(
  `generate-sitemap: wrote ${slugs.length + 2} URLs (${slugs.length} tools, 0 upcoming) to public/sitemap.xml`
);
